
export type GET_WORKSPACES = typeof GET_WORKSPACES;
export type GET_WORKSPACES_SUCCESS = typeof GET_WORKSPACES_SUCCESS;
export type GET_WORKSPACES_FAILURE = typeof GET_WORKSPACES_FAILURE;

export const GET_WORKSPACES = 'GET_WORKSPACES';
export const GET_WORKSPACES_SUCCESS = 'GET_WORKSPACES_SUCCESS';
export const GET_WORKSPACES_FAILURE = 'GET_WORKSPACES_FAILURE';
